export const Routing = {
    Error: `*`,
    Login: `/`,
    Dashboard: `/dashboard`,
    Couriers: `/couriers`,
    CourierCompanies: `/couriers-companies`,
    Customers: `/customers`,
    Sells: `/sells`,
    CustomerLedger: `/customers/:customerId/ledger`,
    Users: `/users`,
    Products: `/products`,
    AccountIncome: `/account/income`,
    AccountExpense: `/account/expense`,
    AccountPendingBill: `/account/pending-bill`,
    AccountDebited: `/account/debited`,
    AccountBankAccounts: `/account/bank-accounts`,
    RouteSetting: `/setting/route-setting`,
    RoleManagement: `/setting/role-management`,
    Forbidden: `/forbidden`
};

export const RouteTitles: Record<string, string> = {
    [Routing.Login]: "Login",
    [Routing.Dashboard]: "Dashboard",
    [Routing.Couriers]: "Couriers",
    [Routing.CourierCompanies]: "Courier Companies",
    [Routing.Customers]: "Customers",
    [Routing.Sells]: "Sells",
    [Routing.CustomerLedger]: "Customer Account",
    [Routing.Users]: "Users",
    [Routing.Products]: "Products",
    [Routing.AccountIncome]: "Account Income",
    [Routing.AccountExpense]: "Account Expense",
    [Routing.AccountPendingBill]: "Pending Bill",
    [Routing.AccountDebited]: "Account Debited",
    [Routing.AccountBankAccounts]: "Bank Accounts",
    [Routing.RouteSetting]: "Route Setting",
    [Routing.RoleManagement]: "Role Management",
    [Routing.Forbidden]: "Forbidden",
};